name: peoplegrid
favicon: null
layout_spectrum: 0.8783574618864805
typography_spectrum: 0.0038911723531782627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17120f'
    - '#c8e3ed'
    - '#f9cb10'
    - '#39454e'
    - '#688381'
  brandStrength: 0.625
  lightness: 0.937380813062191
  saturation: 0.03307104390114546
  rhythmicContrast: 0.43420363729819655
purpose: []
